import {
  WineData,
  StrongDrinksData,
  BeerData,
  LatinAmericaData,
  AsianData,
  CiderData,
} from './alcoholData';

export const ALCOHOLCATEGORIES = [
  {
    title: 'Wine',
    iconUrl: require('../assets/images/categories/wine.jpg'),
    hasSubCategories: false,
    hasColorCategories: true,
    hasContentCategories: true,
    subCategories: [],
    colorCategory: ['Red', 'White', 'Rosé', 'Orange'],
    contentCategory: ['Still', 'Dry', 'Sparkling', 'Dessert', 'Fortified'],
    products: WineData,
  },
  {
    title: 'Strong drinks',
    iconUrl: require('../assets/images/categories/burbon.jpg'),
    hasSubCategories: true,
    hasColorCategories: false,
    hasContentCategories: false,
    subCategories: [
      'Vodka',
      'Whiskey',
      'Brandy',
      'Cognac',
      'Gin',
      'Absinthe',
      'Sambuca',
      'Bourbon',
      'Schnapps',
    ],
    products: StrongDrinksData,
  },
  {
    title: 'Beer',
    iconUrl: require('../assets/images/categories/beer.jpg'),
    hasSubCategories: true,
    hasColorCategories: true,
    hasContentCategories: false,
    subCategories: ['Ale', 'Lager', 'Fruit', 'Others'],
    colorCategory: ['Dark', 'Pale'],
    products: BeerData,
  },
  {
    title: 'Latin America',
    iconUrl: require('../assets/images/categories/tequilla.jpg'),
    hasSubCategories: true,
    hasColorCategories: false,
    hasContentCategories: false,
    subCategories: ['Cauim', 'Chicha', 'Tequila', 'Mezcal', 'Rum'],
    products: LatinAmericaData,
  },
  {
    title: 'Asian',
    iconUrl: require('../assets/images/categories/sake.jpg'),
    hasSubCategories: true,
    hasColorCategories: false,
    hasContentCategories: false,
    subCategories: [
      'Cheongju',
      'Baijiu',
      'Huangjiu',
      'Sake',
      'Sato',
      'Tapey',
      'Soju',
    ],
    products: AsianData,
  },
  {
    title: 'Liqueurs',
    iconUrl: require('../assets/images/categories/liqueur.jpg'),
    hasSubCategories: false,
    hasColorCategories: false,
    hasContentCategories: false,
    subCategories: [],
    products: [],
  },
  {
    title: 'Cider',
    iconUrl: require('../assets/images/categories/cider.jpg'),
    hasSubCategories: false,
    hasColorCategories: false,
    hasContentCategories: false,
    subCategories: [],
    products: CiderData,
  },
  {
    title: 'Juices',
    iconUrl: require('../assets/images/categories/juice.jpg'),
    hasSubCategories: false,
    hasColorCategories: false,
    hasContentCategories: false,
    subCategories: [],
    products: [],
  },
  {
    title: 'Mineral water',
    iconUrl: require('../assets/images/categories/mineral_water.jpg'),
    hasSubCategories: false,
    hasColorCategories: false,
    hasContentCategories: false,
    subCategories: [],
    products: [],
  },
];
