export const WineData = [
  {
    ABV: 11,
    availability: true,
    basePrice: 13,
    finalPrice: 13,
    category: 'Wine',
    colorCategory: 'Rosé',
    contentCategory: 'Dry',
    description:
      'A delicious aperitif, ideal with white fish, light snacks and summer salads. The aroma is elegant, fruity, floral and rich. The taste of the drink is characteristic, pleasantly thick and balanced.',
    discount: 0.1,
    image: 'https://www.thecocktaildb.com/images/ingredients/Prosecco.png',
    ingredientName: '',
    subcategory: '',
    title: 'Astoria Prosecco Spumante',
    volume: 0,
  },
  {
    ABV: 11.5,
    availability: true,
    basePrice: 13.6,
    finalPrice: 13,
    category: 'Wine',
    colorCategory: 'White',
    contentCategory: 'Dry',
    description:
      'An excellent aperitif, goes well with light salads and appetizers of fish and seafood. The aroma is fruity-spicy with pleasant hints of ripe apple, butter and nuts. The taste is fresh, perfectly balanced, pleasant, harmonious.',
    discount: 0.1,
    image: 'https://www.thecocktaildb.com/images/ingredients/Prosecco.png',
    ingredientName: 'Prosecco',
    subcategory: '',
    title: 'Astoria Prosecco Treviso',
    volume: 0.75,
  },
  {
    ABV: 0,
    availability: true,
    basePrice: 11.5,
    finalPrice: 13,
    category: 'Wine',
    colorCategory: 'White',
    contentCategory: 'Sparkling',
    description:
      'Excellent as an aperitif, as an accompaniment to appetizers, salads and many other light meals. Bright aroma with hints of apples, citrus and light creamy notes. The wine has a light, delicate, well-balanced taste with a refreshing aftertaste.',
    discount: 0,
    image: 'https://www.thecocktaildb.com/images/ingredients/Champagne.png',
    ingredientName: 'Champagne',
    subcategory: '',
    title: 'Heretat el Padruell Сava',
    volume: 0.75,
  },
  {
    ABV: 10.4,
    availability: false,
    basePrice: 7,
    finalPrice: 13,
    category: 'Wine',
    colorCategory: 'White',
    contentCategory: 'Sparkling',
    description:
      'Excellent as an aperitif, and also ideally complements light desserts and pastries. Suitable for making cocktails. Its aroma is balanced sweet, berry, with nuances of wild strawberry. The taste is harmonious, pleasant, fruity, with expressive tones of wild strawberries.',
    discount: 0.12,
    image: 'https://www.thecocktaildb.com/images/ingredients/Champagne.png',
    ingredientName: 'Champagne',
    subcategory: '',
    title: 'Fragolino Fiorelli Bianco',
    volume: 0.75,
  },
  {
    ABV: 11.5,
    availability: true,
    category: 'Wine',
    description:
      'Pairs well with fruits, cheeses and desserts. Delicate floral aroma, silky texture and unusually soft aftertaste. With the taste and freshness of white grape varieties, it has a balanced fullness and elegance.',
    discountBig: true,
    discountSmall: false,
    finalPrice: 6.6,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Champagne.png',
    ingredientName: 'Champagne',
    colorCategory: 'White',
    contentCategory: 'Sparkling',
    subcategory: '',
    title: 'Grande France',
    volume: 0.75,
  },
  {
    ABV: 7,
    availability: true,
    category: 'Wine',
    description:
      'It goes well with desserts, fruits, soft cheeses. Intense bouquet with hints of pomegranate. The taste of the drink is pleasant, with hints of ripe pomegranate and a slightly tart aftertaste.',
    discountBig: false,
    discountSmall: false,
    finalPrice: 13,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Wine.png',
    ingredientName: 'Wine',
    colorCategory: 'Rosé',
    contentCategory: 'Dessert',
    subcategory: '',
    title: 'Villa Mare Granatino Rose',
    volume: 0.75,
  },
  {
    ABV: 7.5,
    availability: true,
    category: 'Wine',
    description:
      'It goes well with desserts, fruits, soft cheeses. Intense bouquet with hints of pomegranate. The taste of the drink is pleasant, with hints of ripe pomegranate and a slightly tart aftertaste.',
    discountBig: false,
    discountSmall: false,
    finalPrice: 12.8,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Wine.png',
    ingredientName: 'Wine',
    colorCategory: 'White',
    contentCategory: 'Dessert',
    subcategory: '',
    title: 'Yellow Tail Moscato',
    volume: 0.75,
  },
  {
    ABV: 12,
    availability: true,
    category: 'Wine',
    description:
      'Pairs well with meat dishes and appetizers. Aroma is fruity with hints of ripe red berries, notes of ripe cherries. Full harmonious taste.',
    discountBig: true,
    discountSmall: false,
    finalPrice: 18.4,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Red%20Wine.png',
    ingredientName: 'Red Wine',
    colorCategory: 'Red',
    contentCategory: 'Still',
    subcategory: '',
    title: 'Vino la Casa Rosso',
    volume: 1,
  },
  {
    ABV: 13.5,
    availability: true,
    category: 'Wine',
    description:
      'Gastronomic compatibility - grilled meat, game, soft cheeses. The taste of the drink is elegant, balanced, with soft tannins. Aroma of blackcurrant, ripe cherries, vanilla and plums.',
    discountBig: false,
    discountSmall: true,
    finalPrice: 216,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Red Wine.png',
    ingredientName: 'Red Wine',
    colorCategory: 'Red',
    contentCategory: 'Still',
    subcategory: '',
    title: 'Ropiteau Freres Nuits-Saint-Georges',
    volume: 0.75,
  },
  {
    ABV: 13,
    availability: true,
    category: 'Wine',
    description:
      'Bright aroma reveals perfectly balanced shades of ripe fruits, such as: blackcurrant, raspberry, cherry. Elegant oaky notes of aging.',
    discountBig: true,
    discountSmall: false,
    finalPrice: 56.69,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Red Wine.png',
    ingredientName: 'Red Wine',
    colorCategory: 'Red',
    contentCategory: 'Still',
    subcategory: '',
    title: 'Shabo Grande Reserve',
    volume: 0.75,
  },
  {
    ABV: 15,
    availability: true,
    category: 'Wine',
    description:
      'Its extraordinary taste is better emphasized by hard varieties of cheeses. Intense, warm taste with notes of vanilla and bitter chocolate, a slight shade of red fruits, plum jam at the end.',
    discountBig: false,
    discountSmall: true,
    finalPrice: 74.7,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Red Wine.png',
    ingredientName: 'Red Wine',
    colorCategory: 'Red',
    contentCategory: 'Still',
    subcategory: '',
    title: 'Anno Domini Garbin Vino Rosso',
    volume: 0.75,
  },
  {
    ABV: 12.5,
    availability: true,
    category: 'Wine',
    description:
      'The multifaceted bouquet reveals aromas of linden, acacia and ripe peach, accompanied by noble vanilla notes of oak aging.',
    discountBig: false,
    discountSmall: true,
    finalPrice: 40.5,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Wine.png',
    ingredientName: 'Wine',
    colorCategory: 'Orange',
    contentCategory: 'Dry',
    subcategory: '',
    title: 'Kabaj Rebula',
    volume: 0.75,
  },
];

export const CiderData = [
  {
    ABV: 4.5,
    availability: true,
    category: 'Cider',
    description:
      'Cider is great to drink as an accompaniment to white meat, to various desserts (pancakes, apple pie, cakes).',
    discountBig: true,
    discountSmall: false,
    finalPrice: 3.2,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Cider.png',
    ingredientName: 'Cider',
    colorCategory: '',
    contentCategory: '',
    subcategory: '',
    title: 'Magners Pear',
    volume: 0.56,
  },
  {
    ABV: 7.5,
    availability: false,
    category: 'Cider',
    description:
      'Cider is great to drink as an accompaniment to white meat, to various desserts (pancakes, applepie, cakes). Also good as an aperitif or to quench your thirst on a hot day. The taste of cider is rich, soft, with notes of apples, kvass, slightly sweet, very fresh. Medium body, well balanced, very drinkable.',
    discountBig: false,
    discountSmall: true,
    finalPrice: 7.47,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Cider.png',
    ingredientName: 'Cider',
    colorCategory: '',
    contentCategory: '',
    subcategory: '',
    title: 'Christian Drouin Cidre Brut de Normandie',
    volume: 0.7,
  },
  {
    ABV: 4.5,
    availability: true,
    category: 'Cider',
    description:
      'Cider is great to drink as an accompaniment to white meat, to various desserts (pancakes, apple pie, cakes).',
    discountBig: false,
    discountSmall: false,
    finalPrice: 4,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Apple cider.png',
    ingredientName: 'Apple cider',
    colorCategory: '',
    contentCategory: '',
    subcategory: '',
    title: 'Magners Original',
    volume: 0.56,
  },
  {
    ABV: 4,
    availability: false,
    category: 'Cider',
    description:
      'Cider is great to drink as an accompaniment to white meat, to various desserts (pancakes, apple pie, cakes).',
    discountBig: false,
    discountSmall: false,
    finalPrice: 4,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Cider.png',
    ingredientName: 'Cider',
    colorCategory: '',
    contentCategory: '',
    subcategory: '',
    title: 'Magners Berry',
    volume: 0.56,
  },
  {
    ABV: 4.5,
    availability: true,
    category: 'Cider',
    description:
      'Cider is great to drink as an accompaniment to white meat, to various desserts (pancakes, apple pie, cakes).',
    discountBig: false,
    discountSmall: false,
    finalPrice: 13,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Apple cider.png',
    ingredientName: 'Apple cider',
    colorCategory: '',
    contentCategory: '',
    subcategory: '',
    title: 'Stella Artois',
    volume: 0.56,
  },
];

export const BeerData = [
  {
    ABV: 4.6,
    availability: true,
    category: 'Beer',
    description: '',
    discountBig: true,
    discountSmall: false,
    finalPrice: 1.6,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Lager.png',
    ingredientName: 'Lager',
    colorCategory: 'Pale',
    contentCategory: '',
    subcategory: 'Lager',
    title: 'Estrella Damm Lager',
    volume: 0.5,
  },
  {
    ABV: 5,
    availability: false,
    category: 'Beer',
    description:
      'Beer goes well with snacks, pizza, potatoes, snacks, simple meat dishes.',
    discountBig: false,
    discountSmall: false,
    finalPrice: 2,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Lager.png',
    ingredientName: 'Lager',
    colorCategory: 'Pale',
    contentCategory: '',
    subcategory: 'Lager',
    title: 'Stammgast Lager',
    volume: 0.5,
  },
  {
    ABV: 7.5,
    availability: true,
    category: 'Ale',
    description: 'Ale 1',
    discountBig: true,
    discountSmall: false,
    finalPrice: 2.4,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Ale.png',
    ingredientName: 'Ale',
    colorCategory: 'Dark',
    contentCategory: '',
    subcategory: 'Ale',
    title: 'Ale 1',
    volume: 0.75,
  },
  {
    ABV: 6,
    availability: true,
    category: 'Ale',
    description: 'Ale 2',
    discountBig: false,
    discountSmall: false,
    finalPrice: 2,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Ale.png',
    ingredientName: 'Ale',
    colorCategory: 'Dark',
    contentCategory: '',
    subcategory: 'Ale',
    title: 'Ale 2',
    volume: 0.75,
  },
  {
    ABV: 6.5,
    availability: true,
    category: 'Ale',
    description: 'Ale 3',
    discountBig: false,
    discountSmall: false,
    finalPrice: 3,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Ale.png',
    ingredientName: 'Ale',
    colorCategory: 'Dark',
    contentCategory: '',
    subcategory: 'Ale',
    title: 'Ale 3',
    volume: 0.75,
  },
  {
    ABV: 5.5,
    availability: true,
    category: 'Ale',
    description: 'Ale 4',
    discountBig: false,
    discountSmall: false,
    finalPrice: 2,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Ale.png',
    ingredientName: 'Ale',
    colorCategory: 'Pale',
    contentCategory: '',
    subcategory: 'Ale',
    title: 'Ale 4',
    volume: 0.75,
  },
  {
    ABV: 3.5,
    availability: true,
    category: 'Ale',
    description: 'Ale ',
    discountBig: false,
    discountSmall: false,
    finalPrice: 5,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Ale.png',
    ingredientName: 'Ale',
    colorCategory: 'Fruit',
    contentCategory: '',
    subcategory: 'Fruit',
    title: 'Ale 5',
    volume: 0.75,
  },
];

export const AsianData = [
  {
    ABV: 10.5,
    availability: true,
    category: 'Asian',
    description: 'Cheongju 1',
    discountBig: false,
    discountSmall: false,
    finalPrice: 23,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Cheongju',
    title: 'Cheongju 1',
    volume: 0.75,
  },
  {
    ABV: 9.5,
    availability: false,
    category: 'Asian',
    description: 'Cheongju 2',
    discountBig: true,
    discountSmall: false,
    finalPrice: 12.6,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Cheongju',
    title: 'Cheongju 2',
    volume: 0.75,
  },
  {
    ABV: 11.5,
    availability: true,
    category: 'Asian',
    description: 'Baijiu',
    discountBig: true,
    discountSmall: false,
    finalPrice: 8.4,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Baijiu',
    title: 'Baijiu',
    volume: 0.75,
  },
  {
    ABV: 11,
    availability: true,
    category: 'Asian',
    description: 'Baijiu 2',
    discountBig: false,
    discountSmall: true,
    finalPrice: 12.96,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: 'Baijiu',
    contentCategory: '',
    subcategory: '',
    title: 'Baijiu 2 ',
    volume: 0.75,
  },
  {
    ABV: 11,
    availability: true,
    category: 'Asian',
    description: 'Baijiu 3',
    discountBig: false,
    discountSmall: true,
    finalPrice: 12.06,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Baijiu',
    title: 'Baijiu 3 ',
    volume: 0.75,
  },
  {
    ABV: 3,
    availability: false,
    category: 'Asian',
    description: 'Huangjiu',
    discountBig: false,
    discountSmall: true,
    finalPrice: 3.06,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Huangjiu',
    title: 'Huangjiu ',
    volume: 0.55,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Asian',
    description: 'Sake',
    discountBig: false,
    discountSmall: true,
    finalPrice: 12.6,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Sake',
    title: 'Sake ',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Asian',
    description: 'Sato',
    discountBig: false,
    discountSmall: true,
    finalPrice: 12.6,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Sato',
    title: 'Sato',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Asian',
    description: 'Tapey',
    discountBig: false,
    discountSmall: true,
    finalPrice: 12.6,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Tapey',
    title: 'Tapey',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Asian',
    description: 'Tapey 2',
    discountBig: false,
    discountSmall: true,
    finalPrice: 12.6,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Tapey',
    title: 'Tapey 2',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Asian',
    description: 'Tapey 3',
    discountBig: false,
    discountSmall: true,
    finalPrice: 12.6,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Tapey',
    title: 'Tapey 3',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Asian',
    description: 'Soju',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/sake.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Soju',
    title: 'Soju',
    volume: 0.75,
  },
];

export const LatinAmericaData = [
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Cauim',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Tequila.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Cauim',
    title: 'Cauim',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Cauim 2',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Tequila.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Cauim',
    title: 'Cauim 2',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Chicha',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Tequila.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Chicha',
    title: 'Chicha',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Chicha 2',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Tequila.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Chicha',
    title: 'Chicha 2',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Chicha 3',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Tequila.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Chicha',
    title: 'Chicha 3',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Tequila',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Tequila.png',
    ingredientName: 'Tequila',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Tequila',
    title: 'Tequila',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: false,
    category: 'Latin America',
    description: 'Mezcal',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Mezcal.png',
    ingredientName: '',
    colorCategory: '',
    contentCategory: '',
    subcategory: '',
    title: 'Mezcal',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Light rum',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Light rum.png',
    ingredientName: 'Light rum',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Rum',
    title: 'Light rum',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Light rum 2',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Light rum.png',
    ingredientName: 'Light rum',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Rum',
    title: 'Light rum 2',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Light rum 3',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Light rum.png',
    ingredientName: 'Light rum',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Rum',
    title: 'Light rum 3',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Light rum 4',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Light rum.png',
    ingredientName: 'Light rum',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Rum',
    title: 'Light rum 4',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Dark rum',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Dark rum.png',
    ingredientName: 'Dark rum',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Rum',
    title: 'Dark rum',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Dark rum 2',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Dark rum.png',
    ingredientName: 'Dark rum',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Rum',
    title: 'Dark rum 2',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Dark rum 3',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Dark rum.png',
    ingredientName: 'Dark rum',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Rum',
    title: 'Dark rum 3',
    volume: 0.75,
  },
  {
    ABV: 8.5,
    availability: true,
    category: 'Latin America',
    description: 'Spiced rum',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Spiced rum.png',
    ingredientName: 'Spiced rum',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Rum',
    title: 'Spiced rum',
    volume: 0.75,
  },
];

export const StrongDrinksData = [
  {
    ABV: 40,
    availability: true,
    category: 'Strong drinks',
    description: 'Lemon vodka',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Lemon vodka.png',
    ingredientName: 'Lemon vodka',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Vodka',
    title: 'Lemon vodka',
    volume: 0.75,
  },
  {
    ABV: 38.5,
    availability: true,
    category: 'Strong drinks',
    description: 'Bourbon',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Bourbon.png',
    ingredientName: 'Bourbon',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Bourbon',
    title: 'Bourbon',
    volume: 0.75,
  },
  {
    ABV: 36,
    availability: true,
    category: 'Strong drinks',
    description: 'Apple brandy',
    discountBig: false,
    discountSmall: true,
    finalPrice: 6.3,
    hasDiscount: true,
    image: 'https://www.thecocktaildb.com/images/ingredients/Apple brandy.png',
    ingredientName: 'Apple brandy',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Brandy',
    title: 'Apple brandy',
    volume: 0.75,
  },
  {
    ABV: 42,
    availability: true,
    category: 'Strong drinks',
    description: 'Whiskey',
    discountBig: false,
    discountSmall: false,
    finalPrice: 13,
    hasDiscount: false,
    image: 'https://www.thecocktaildb.com/images/ingredients/Whiskey.png',
    ingredientName: 'Whiskey',
    colorCategory: '',
    contentCategory: '',
    subcategory: 'Whiskey',
    title: 'Whiskey',
    volume: 0.75,
  },
];
